echo "
"
echo "████████████████████"
echo "Mᴀᴅᴇ ʙʏ ᴠɪʟʟᴀɢᴇ/Eʀʀᴏʀ"
echo "Mᴏʀᴀʟ sᴜᴘᴘʀᴏᴛ - ᴠɪɴᴇx
echo "Aᴜᴛᴏᴍᴀᴛᴇᴅ ғɪʟᴇs"
echo "Pʟᴀʏ sᴀғᴇ ғᴏʀ ʀᴀɴᴋ ᴘᴜsʜ"
echo "████████████████████"
echo ""
echo " [AFTER RUN PUBG FROM TERMUX] "
echo " [LOG IN AND MINIMIZE] "
echo " [WHEN YOU COME TO LOBBY] "
echo "
"
echo -e " [THEN] "
echo -e " [CHECK YOUR DOWNLOAD FOLDER] "
echo -e " [THERE WILL BE A FOLDER NAMED TiAmo] "
echo -e " [IN THAT FOLDER] "
echo -e " [YOU FIND A LOBBY SH] "
echo -e " [RUN LOBBY SH] "
echo "
"
sleep 5
echo "███████▒▒▒▒▒60%"
echo ""
sleep 2
echo "███████████▒▒▒80%"
echo ""
sleep 3
echo "████████████████100%"
echo ""
echo " Dᴏɴᴇ "
echo "-_-_-_-_-_"
